Rider 2020.3 support
olsh/resharper-structured-logging pull request #15
Opened 2020-12-06 15:37 UTC by vladyslav-burylov

Note: smoke test executed against JetBrains Rider 2020.3 EAP 10, build #RD-203.5981.86, built on December 2, 2020

2020-12-10 19:45 UTC, olsh commented
Thanks for your contribution! 👍

2020-12-10 19:51 UTC, olsh requested changes
I'm actually not sure if it's OK to set wave to 203 with SDK 202.
Probably we need to update SDK to 203 EAP if we want to target wave 203.

2020-12-10 19:51 UTC, olsh commented on src/ReSharper.Structured.Logging/ReSharper.Structured.Logging.Rider.csproj
> +    <VersionPrefix>2020.3.1</VersionPrefix>
The version should be the same as SDK

2020-12-10 19:51 UTC, olsh commented on src/ReSharper.Structured.Logging/ReSharper.Structured.Logging.csproj
> +    <VersionPrefix>2020.3.1</VersionPrefix>
The version should be the same as SDK

2020-12-10 19:51 UTC, olsh commented on src/rider-structured-logging/META-INF/plugin.xml
> +  <version>2020.3.1</version>
No need to update the file. It's updated automatically by cake.

2020-12-11 14:39 UTC, vladyslav-burylov commented
Hi @olsh - thank you - that all make sense to me. I have upgraded references to SDK 203-eap10 for now. My assumption is that you would like to wait final release of the SDK/Rider, so I propose to keep this pull request open.

I will do final upgrade once public version will be available - will let you know.

Thanks!

2020-12-11 14:40 UTC, vladyslav-burylov commented on src/ReSharper.Structured.Logging/ReSharper.Structured.Logging.csproj
> +    <VersionPrefix>2020.3.1</VersionPrefix>
fixed

2020-12-11 14:40 UTC, vladyslav-burylov commented on src/ReSharper.Structured.Logging/ReSharper.Structured.Logging.Rider.csproj
> +    <VersionPrefix>2020.3.1</VersionPrefix>
fixed

2020-12-14 14:47 UTC, merged

2020-12-14 14:48 UTC, olsh commented
Thank you! 👍